<?php
	if ( $this->getProcessor() && $this->getProcessor()->getMail() && $this->getOrder()  )
	{
		if ( Mage::getStoreConfigFlag('auit_pdf/general/attach_to_email_shipment',$this->getOrder()->getStoreId()) )
		{

			//AITOC Rewrite Probleme
			$mail = $this->getProcessor()->getMail();
			$parts = $mail->getParts();

			// 10.11.2015
			$models = array();
			$processVariables = $this->getProcessor()->getProcessVariables();
			if ( $processVariables && isset($processVariables['shipment']) )
				$models =array($processVariables['shipment']);
			else
				$models =$this->getOrder()->getShipmentsCollection() ;
				
			$pdf_filename = Mage::helper('auit_pdf')->getPdfFName('fname_to_email_shipment',$models);
			$bfound=false;
			foreach ( $parts as $part )
			{
				/** @var Zend_Mime_Part $part */
				if ( $part->filename == $pdf_filename )
				{
					$bfound=true;
					break;
				}
			}
			if ( !$bfound )
			{
				$processVariables = $this->getProcessor()->getProcessVariables();
				if ( $processVariables && isset($processVariables['shipment']) )
				{
					$pdf = Mage::getModel('auit_pdf/shipment')->getPdf(array($processVariables['shipment']));
				}
				else {				
					$pdf = Mage::getModel('auit_pdf/shipment')->getPdf($this->getOrder()->getShipmentsCollection() );
				}
				$mail->createAttachment($pdf->render(),Zend_Mime::TYPE_OCTETSTREAM,Zend_Mime::DISPOSITION_ATTACHMENT,Zend_Mime::ENCODING_BASE64, $pdf_filename);
				Mage::helper('auit_pdf')->addAttachments('email_attachments_shipment',$mail,$this->getOrder()->getShipmentsCollection());
			}
		}
	}
?>
