<?php 
?>
<?php if ( $order=$this->getOrder() ) : ?>

<?php
	$shippingInfoModel = Mage::getModel('shipping/info');
	$shippingInfoModel->setProtectCode($order->getProtectCode());
	$shippingInfoModel->setOrderId($order->getId())->getTrackingInfoByOrder();
?>	
	
	<?php if (count($shippingInfoModel->getTrackingInfo()) > 0) :?>
	<table class="tracking-info">
		<?php foreach ( $shippingInfoModel->getTrackingInfo() as $shipid => $_result ) :?>
        
			<?php $_id = 0; foreach($_result as $track): ?>
                <?php if(is_object($track)): ?>
                    <tr>
                        <th class="label"><?php echo $this->__('Tracking Number:'); ?></th>
                        <td class="value"><?php echo $track->getTracking(); ?></td>
                    </tr>
                    <?php if ($track->getCarrierTitle()): ?>
                    <tr>
                        <th class="label"><?php echo $this->__('Carrier:'); ?></th>
                        <td class="value"><?php echo $track->getCarrierTitle(); ?></td>
                    </tr>
                    <?php endif; ?>
                    <?php if($track->getErrorMessage()): ?>
                    <tr>
                        <th class="label"><?php echo $this->__('Error:'); ?></th>
                        <td class="error"><?php echo $track->getErrorMessage();?></td>
                    </tr>
                    <?php elseif($track->getTrackSummary()): ?>
                    <tr>
                        <th class="label"><?php echo $this->__('Info:'); ?></th>
                        <td class="value"><?php echo $track->getTrackSummary(); ?></td>
                    </tr>
                    <?php elseif($track->getUrl()): ?>
                    <tr>
                        <th class="label"><?php echo $this->__('Track:'); ?></th>
                        <td class="value"><a href="<?php echo $track->getUrl(); ?>" onclick="this.target='_blank'"><?php echo $track->getUrl(); ?></a></td>
                    </tr>
                    <?php else: ?>
                        <?php if ($track->getStatus()): ?>
                        <tr>
                            <th class="label"><?php echo $this->__('Status:'); ?></th>
                            <td class="value"><?php echo $track->getStatus(); ?></td>
                        </tr>
                        <?php endif; ?>

                        <?php if ($track->getDeliverydate()): ?>
                        <tr>
                            <th class="label"><?php echo $this->__('Delivered on:'); ?></th>
                            <td class="value"><?php echo $this->formatDeliveryDateTime($track->getDeliverydate(),$track->getDeliverytime()); ?></td>
                        </tr>
                        <?php endif; ?>

                        <?php if ($track->getSignedby()): ?>
                        <tr>
                            <th class="label"><?php echo $this->__('Signed by:'); ?></th>
                            <td class="value"><?php echo $track->getSignedby(); ?></td>
                        </tr>
                        <?php endif; ?>

                        <?php if ($track->getDeliveryLocation()): ?>
                        <tr>
                            <th class="label"><?php echo $this->__('Delivered to:'); ?></th>
                            <td class="value"><?php echo $track->getDeliveryLocation(); ?></td>
                        </tr>
                        <?php endif; ?>

                        <?php if ($track->getShippedDate()): ?>
                        <tr>
                            <th class="label"><?php echo $this->__('Shipped or billed on:'); ?></th>
                            <td class="value"><?php echo $track->getShippedDate(); ?></td>
                        </tr>
                        <?php endif; ?>

                        <?php if ($track->getService()): ?>
                        <tr>
                            <th class="label"><?php echo $this->__('Service Type:'); ?></th>
                            <td class="value"><?php echo $track->getService(); ?></td>
                        </tr>
                        <?php endif; ?>

                        <?php if ($track->getWeight()): ?>
                        <tr>
                            <th class="label"><?php echo $this->__('Weight:'); ?></th>
                            <td class="value"><?php echo $track->getWeight(); ?></td>
                        </tr>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php elseif(isset($track['title']) && isset($track['number']) && $track['number']): ?>
                    <!--if the tracking is custom value-->
                    <tr>
                        <th class="label"><?php echo ($track['title'] ? $this->escapeHtml($track['title']) : $this->__('N/A')); ?>:</th>
                        <td class="value"><?php echo (isset($track['number']) ? $this->escapeHtml($track['number']) : ''); ?></td>
                    </tr>
                <?php endif; ?>
			<?php endforeach;?>
		<?php endforeach;?>
	</table>
	<?php endif;?>
<?php endif;?>