<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

/**
 * @category   	TechDivision
 * @package    	TechDivision_Easylog
 * @copyright  	Copyright (c) 2010 <info@techdivision.com> - TechDivision GmbH
 * @license    	http://opensource.org/licenses/osl-3.0.php
 * 				Open Software License (OSL 3.0)
 * @author      Johann Zelger <j.zelger@techdivision.com>
 */

?>
<script type="text/javascript">
//<![CDATA[
 
    var EasylogTierpriceModel = Class.create();
    EasylogTierpriceModel.prototype = {
    	objectPrefix : "row_carriers_easylog_dhl_",
    	objectTargets : new Array("pricetable_","servicetable_"),
    	initialize : function()
		{
			this.reload = false;
			this.methodSelector = $('carriers_easylog_dhl_selected_methods');
			if ($('carriers_easylog_dhl_selected_methods')) {
				this.methodSelector.observe(
					'change',
					this.update.bind(this)
				);
				this.update();
			}
		},
		update: function()
		{
			for (i=0; i < this.methodSelector.options.length; i++) {
				for (ii=0; ii < this.objectTargets.length; ii++) {
					var tierpriceObject = $(
						this.objectPrefix + this.objectTargets[ii] 
						+ this.methodSelector.options[i].value
					);
					if (tierpriceObject) {
						if (this.methodSelector.options[i].selected) {
							tierpriceObject.show();
						} else {
							tierpriceObject.hide();
						}
					}
				}
			}
		}
    }

    easylogTierprice = new EasylogTierpriceModel();
//]]>
</script>