<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

/**
 * @category   	TechDivision
 * @package    	TechDivision_Easylog
 * @copyright  	Copyright (c) 2010 <info@techdivision.com> - TechDivision GmbH
 * @license    	http://opensource.org/licenses/osl-3.0.php
 * 				Open Software License (OSL 3.0)
 * @author      Sebastian Ertner <sebastian.ertner@netresearch.de>
 */
?>

<table cellspacing="0" class="switcher" width="100%" class="form-list">
    <col width="220px" />
    <col />
    <thead>
        <tr>
            <th colspan="2">
                <?php echo $this->escapeHtml($this->getFieldsetLabel()) ?>
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><?php echo $this->__('Version'); ?></td>
            <td><?php echo $this->getVersion(); ?></td>
        </tr>
        <tr>
            <td><?php echo $this->__('Find more at'); ?></td>
            <td><a href="http://de.nr-apps.com/store/dhl-easylog.html">http://de.nr-apps.com/store/dhl-easylog.html</a></td>
        </tr>
        <tr>
            <td class="label"><?php echo $this->__('Need support? Contact us'); ?></td>
            <?php
                $mageVersion = Mage::getVersion();
                if (is_callable('Mage::getEdition')) {
                    $mageVersion = Mage::getEdition() . ' ' . $mageVersion;
                }
                $bodyInfo = array(
                    '',
                    '===',
                    'Magento version:    '  . $mageVersion,
                    'EasyLog app version: ' . $this->getVersion(),
                    'Shop URI:           '  . Mage::getBaseUrl()
                );
            ?>
            <td><a href="mailto:<?php echo Mage::helper('easylog/data')->getSupportMail(); ?>?body=<?php echo rawurlencode(implode("\n", $bodyInfo)) ?>"><?php echo Mage::helper('easylog/data')->getSupportMail() ?></a></td>
        </tr>
    </tbody>
</table>