<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

/**
 * @category   	TechDivision
 * @package    	TechDivision_Easylog
 * @copyright  	Copyright (c) 2010 <info@techdivision.com> - TechDivision GmbH
 * @license    	http://opensource.org/licenses/osl-3.0.php
 * 				Open Software License (OSL 3.0)
 * @author      Johann Zelger <j.zelger@techdivision.com>
 */

?>
<?php if ($this->getTrackingIds()): ?>
	<div style="position:fixed;width:100%;height:100%;">
		<iframe src="<?php echo $this->getTrackingUrl() ?>" style="display:block;border:none;width:100%;height:100%;"></iframe>
	</div>
<?php else: ?>
	<?php echo $this->__('Ihre Sendungsverfolung kann leider nicht angezeigt werden.');?>
<?php endif;?>