<?php $_order = $this->getOrder() ?>
<?php $_invoice = $this->getInvoice() ?>
<?php if($_invoice): ?>
    <?php $_invoices = array($_invoice); ?>
<?php else: ?>
    <?php $_invoices = $_order->getInvoiceCollection() ?>
<?php endif; ?>
<?php if ( $text = $this->getBuilBeforeTableText()) :?>
	<div class="text-before"><?php echo $text; ?></div>
<?php endif;?>
<?php foreach ($_invoices as $_invoice): ?>
  <table class="data-table invoice" border="0" cellpadding="0" cellspacing="0" >
  	<thead>
        <tr class="head">
          <th class="col-sku"><?php echo $this->__('Artikelnummer') ?></th>
          <th class="col-product"><?php echo $this->__('Artikel') ?></th>
          <th class="col-price"><?php echo $this->__('Preis') ?></th>
          <th class="col-qty"><?php echo $this->__('Anzahl') ?></th>
          <th class="col-subtotal"><?php echo $this->__('Gesamt') ?></th>
        </tr>
		</thead>
    <tbody>
    <?php $_items = $_invoice->getItemsCollection(); ?>
    <?php foreach ($_items as $_item): ?>
      <?php if ($_item->getOrderItem()->getParentItem()) continue; ?>
      <?php $_product = Mage::getModel('catalog/product')->load($_item->getData('product_id')); ?>
      <tr nobr="true">
        <td class="col-sku">
          <?php echo $_product->getSku() ?>
        </td>
        <td class="col-product">
					<?php echo $_item->getName() ?>
        </td>
        <td class="col-price">
					<?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
					<?php echo Mage::helper('core')->currency($_incl, true, false) ?>
				</td>
        <td class="col-qty">
					<?php echo intval($_item->getQty()) ?>
				</td>
        <td class="col-subtotal">
					<?php echo Mage::helper('core')->currency($this->helper('checkout')->getSubtotalInclTax($_item), true, false) ?>
				</td>
      </tr>
    <?php endforeach; ?>
    </tbody>
    <tfoot>
      <tr><td colspan="5">&nbsp;</td></tr>
      <?php echo $this->getInvoiceTotalsHtml($_invoice); ?>
    </tfoot>
  </table>
<?php if ( $text = $this->getBuildAfterTableText()) :?>
	<br />
	<div class="text-after"><?php echo $text; ?></div>
<?php endif;?>
<?php endforeach; ?>
